name: API - Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "packages/api/**"
      - "packages/utils/**"
      - "Dockerfile.api"
      - "go.mod"
      - "go.sum"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -f Dockerfile.api -t ${{ secrets.DOCKERHUB_USERNAME }}/editor-api:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/editor-api:latest
